version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - API_TOKEN=$API_TOKEN
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: [ "uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0" ,"--port", "8000" ]